name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Package Cache
      run: sudo apt-get update

    - name: Install SDL2 Development Libraries
      run: sudo apt-get install libsdl2-dev

    - name: Install Additional Dependencies
      run: |
        sudo apt-get install -y \
          libsdl2-ttf-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          portaudio19-dev \
          libportmidi-dev

    - name: Build and Install SDL2_mixer with CMake
      run: |
        git clone https://github.com/libsdl-org/SDL_mixer.git
        mkdir SDL_mixer/build
        cd SDL_mixer/build
        cmake ..
        make
        sudo make install
        cd ../../
        rm -rf SDL_mixer

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Compile and Run C Program
      run: |
        gcc -o audio audio.c -lSDL2 -lSDL2_mixer
        ./audio

    - name: Run tests
      run: pytest tests
