name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Package Cache
      run: sudo apt-get update

<<<<<<< HEAD
=======
        
    - name: Install SDL2 Development Libraries
      run: sudo apt-get install libsdl2-dev
    
    - name: Install Additional Dependencies
      run: |
        sudo apt-get install -y \
          libsdl2-ttf-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          portaudio19-dev \
          libportmidi-dev
    
>>>>>>> e10ccf5857d45b68027dc4a721d350b1719105de
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest tests
