name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: List Python files
      run: ls *.py
    - name: Update Package Cache
      run: sudo apt-get update

    - name: Install SDL2 Development Libraries
      run: sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libpython3-dev
    
    - name: Set SDL_CONFIG
      run: echo "SDL_CONFIG=/usr/bin/sdl2-config" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Upgrade pip
      run: pip install --upgrade pip

    - name: Install pygame
      run: pip install https://github.com/pygame/pygame/releases/download/2.0.1/pygame-2.0.1-cp39-cp39-manylinux1_x86_64.whl

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: List installed packages
      run: pip freeze

    - name: Run tests
      run: pytest tests
      working-directory: 
